/*
 * User authentication API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DefaultApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <param name="email"></param>
        /// <response code="201">Succesful response - returns a JWT.</response>
        /// <response code="409">Error response - couldn&#x27;t create user conflict</response>
        /// <response code="500">Error response - unexpected error occurred</response>
        [HttpPost]
        [Route("/register-user/{email}")]
        [ValidateModelState]
        [SwaggerOperation("RegisterUserEmailPost")]
        [SwaggerResponse(statusCode: 201, type: typeof(string), description: "Succesful response - returns a JWT.")]
        [SwaggerResponse(statusCode: 409, type: typeof(BadResponse), description: "Error response - couldn&#x27;t create user conflict")]
        [SwaggerResponse(statusCode: 500, type: typeof(BadResponse), description: "Error response - unexpected error occurred")]
        public virtual IActionResult RegisterUserEmailPost([FromRoute][Required]string email)
        { 
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default(string));

            //TODO: Uncomment the next line to return response 409 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(409, default(BadResponse));

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default(BadResponse));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<string>(exampleJson)
                        : default(string);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
