openapi: 3.0.0
info:
  version: 1.0.0
  title: Resource API
  description: API for managing Resources

paths:
  # =========================
  # CREATE
  # =========================
  /resources:
    post:
      operationId: createResource
      summary: Create a new resource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateResourceCommandDto'
      responses:
        '201':
          description: Resource created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseDto'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'

    # =========================
    # READ (LIST)
    # =========================
    get:
      operationId: getResources
      summary: Get filtered list of resources
      parameters:
        - $ref: '#/components/parameters/NameQueryParam'
        - $ref: '#/components/parameters/TypeQueryParam'
        - $ref: '#/components/parameters/LocationQueryParam'
        - $ref: '#/components/parameters/IsAvailableQueryParam'
        - $ref: '#/components/parameters/MinPriceQueryParam'
        - $ref: '#/components/parameters/MaxPriceQueryParam'
      responses:
        '200':
          description: List of resources
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseDto'
        '500':
          $ref: '#/components/responses/ErrorResponse'

  # =========================
  # READ (SINGLE)
  # =========================
  /resources/{id}:
    get:
      operationId: getResourceById
      summary: Get a single resource by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Resource found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseDto'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'

    # =========================
    # UPDATE
    # =========================
    put:
      operationId: updateResourceById
      summary: Update an existing resource
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateResourceByIdCommandDto'
      responses:
        '200':
          description: Resource updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseDto'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'

    # =========================
    # DELETE
    # =========================
    delete:
      operationId: deleteResourceById
      summary: Delete a resource by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Resource deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseDto'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'

components:
  # =========================
  # DTOs
  # =========================

  # Created to get a overview of handled errorcodes
  schemas:
    HttpStatusCodeEnum:
      type: integer
      description: HTTP status code
      # OK -> 200
      # Created -> 201
      # NoCentent -> 204
      # BadRequest -> 400
      # NotFound -> 404
      # Conflict -> 409
      # InternalServerError -> 500


    # Primary return Wrapper. Now that IAction is not avaidable in NSwag
    ApiResponseDto:
      type: object
      properties:
        statusCode:
          $ref: '#/components/schemas/HttpStatusCodeEnum'
        message:
          type: string
          nullable: true
        resources:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/ResourceResponseDto'

    ResourceResponseDto:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
        basePrice:
          type: number
          format: decimal
        location:
          type: integer
        isAvailable:
          type: boolean
        description:
          type: string
        rowVersion:
          type: string
          format: byte

    CreateResourceCommandDto:
      type: object
      required:
        - name
        - type
        - basePrice
        - location
      properties:
        name:
          type: string
        type:
          type: string
        basePrice:
          type: number
          format: decimal
        location:
          type: integer
        description:
          type: string

    UpdateResourceByIdCommandDto:
      type: object
      required:
        - rowVersion
      properties:
        name:
          type: string
        type:
          type: string
        basePrice:
          type: number
          format: decimal
        location:
          type: integer
        description:
          type: string
        isAvailable:
          type: boolean
        rowVersion:
          type: string
          format: byte

  # =========================
  # Generic Error Response. All Erros use the same format
  # =========================
  responses:
    ErrorResponse:
      description: Standard API error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponseDto'

  # =========================
  # Parameters for queries
  # =========================
  parameters:
    NameQueryParam:
      name: name
      in: query
      required: false
      schema:
        type: string

    TypeQueryParam:
      name: type
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
      style: form
      explode: true
      description: Multi-value filter for resource types

    LocationQueryParam:
      name: location
      in: query
      required: false
      schema:
        type: integer

    IsAvailableQueryParam:
      name: isAvailable
      in: query
      required: false
      schema:
        type: boolean

    MinPriceQueryParam:
      name: minPrice
      in: query
      required: false
      schema:
        type: number
        format: decimal

    MaxPriceQueryParam:
      name: maxPrice
      in: query
      required: false
      schema:
        type: number
        format: decimal
