openapi: 3.0.0
info:
    version: 1.0.0
    title: Resource API

paths:
  '/resource':
    summary: Path to create a resource
    description: Creates a new resource in the system
    post:
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createResourceDto'

        responses:
          '201':
            description: Successful response - returns the created resource.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/resourceResponse'

          '400':
            $ref: '#/components/responses/400Error'

          '409':
            $ref: '#/components/responses/409Error'

          '500':
            $ref: '#/components/responses/500Error'

components:
  schemas:

    createResourceDto:
      type: object
      required:
        - name
        - type
        - basePrice
        - location
      properties:
        name:
          type: string
        type:
          type: string
        basePrice:
          type: number
          format: decimal
        location:
          type: integer
        description:
          type: string
          nullable: true

    resourceResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
        basePrice:
          type: number
          format: decimal
        location:
          type: integer
        description:
          type: string
          nullable: true
        isAvailable:
          type: boolean

    badResponse:
      type: object
      properties:
        message:
          type: string

  responses:
    400Error:
      description: Error response - Invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/badResponse'

    409Error:
      description: Error response - Resource conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/badResponse'

    500Error:
      description: Error response - unexpected error occurred
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/badResponse'
