CREATE DATABASE IF NOT EXISTS authdb;
USE authdb;

-- Create user tabel
CREATE TABLE IF NOT EXISTS `User` (
    `Id` INT AUTO_INCREMENT PRIMARY KEY,
    'Role' VARCHAR(50) NOT NULL DEFAULT 'Guest',
    `Email` VARCHAR(255) NOT NULL,
    'Otp' INT DEFAULT 0,
    'OtpExpiryTime' DATETIME DEFAULT NULL
);