services:
  customers-service:
    build:
      context: .
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=server=authdb;port=3306;database=authdb;user=root;password=root
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      - .:/docker-entrypoint-initdb.d

volumes:
  mysql_data: